[package]
name = "sokol-rs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sokol = { version="*", git="https://github.com/floooh/sokol-rust.git" }

